create database DB_ecommerce;

USE DB_ecommerce;

create table IF NOT EXISTS TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
MARCA VARCHAR (255),
PRECO DECIMAL,
QUANTIDADE INT, 
DESCONTO BOOLEAN,
PRIMARY KEY(ID)
);

INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Bicicleta", "Caloi", 3000, 49, true);
INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Mouse", "xwz", 120, 160, false);
INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Diario", "Tilibra", 29.90, 200, true);
INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Chocolate", "Lacta", 4.59, 390, false);
INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Chaveiro", "pri", 18.90, 147, false);
INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Fone de Ouvido", "tbs", 220, 180, true);
INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Coleira pet", "pet", 59.60, 200, true);
INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Capacete", "Caloi", 600, 30, true);
INSERT INTO TB_PRODUTOS (NOME, MARCA, PRECO, QUANTIDADE, DESCONTO) values ("Celular", "moto", 4000, 21, true);


select * from tb_produtos;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 500;
SELECT * FROM TB_PRODUTOS WHERE PRECO < 500;

UPDATE TB_PRODUTOS
SET NOME = "CADERNO"  
WHERE id = 3;