CREATE DATABASE db_farmacia_bem_estar;

USE db_farmacia_bem_estar;

CREATE TABLE IF NOT EXISTS tb_categoria(
ID BIGINT AUTO_INCREMENT,
MARCA VARCHAR (255) NOT NULL,
TIPO VARCHAR (255) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS tb_produtos(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (255),
PRECO DOUBLE,
PROMOCAO BOOLEAN, 
PRESCRICAO BOOLEAN,
PRIMARY KEY(ID),
CATEGORIA BIGINT,
FOREIGN KEY (CATEGORIA) REFERENCES tb_categoria(ID)
);

INSERT INTO tb_categoria (MARCA, TIPO) values ("pro", "cosmeticos");
INSERT INTO tb_categoria (MARCA, TIPO) values ("life", "suplemento");
INSERT INTO tb_categoria (MARCA, TIPO) values ("mel", "remedios");
INSERT INTO tb_categoria (MARCA, TIPO) values ("joy", "camisinha");
 
INSERT INTO tb_produtos (NOME, PRECO, PROMOCAO, PRESCRICAO, CATEGORIA) VALUES ("BASE", 34, TRUE, FALSE, 1);
INSERT INTO tb_produtos (NOME, PRECO, PROMOCAO, PRESCRICAO, CATEGORIA) VALUES ("DIPIRONA", 10, FALSE, FALSE, 4);
INSERT INTO tb_produtos (NOME, PRECO, PROMOCAO, PRESCRICAO, CATEGORIA) VALUES ("ESCOVA", 70, TRUE, FALSE, 1);
INSERT INTO tb_produtos (NOME, PRECO, PROMOCAO, PRESCRICAO, CATEGORIA) VALUES ("AMOXILIN", 80, TRUE, TRUE, 4);
INSERT INTO tb_produtos (NOME, PRECO, PROMOCAO, PRESCRICAO, CATEGORIA) VALUES ("L", 12, TRUE, FALSE, 5);

SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_PRODUTOS;
SELECT * FROM TB_PRODUTOS WHERE PRECO >50;
SELECT * FROM TB_PRODUTOS WHERE PRECO > 5 AND PRECO <60;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PRODUTOS INNER JOIN tb_categoria ON tb_categoria.ID = TB_PRODUTOS.CATEGORIA;
